export const airlineCodeToName: Record<string, string> = {
  EXS: "Jet2.com",
  BA: "British Airways",
  U2: "easyJet",
  FR: "Ryanair",
  W9: "Wizz Air",
  DY: "Norwegian",
  SK: "SAS",
  KL: "KLM",
  AF: "Air France",
  LH: "Lufthansa",
  IB: "Iberia",
  TK: "Turkish Airlines",
  SQ: "Singapore Airlines",
  EK: "Emirates",
  QR: "Qatar Airways",
  CX: "Cathay Pacific",
  JL: "Japan Airlines",
  NH: "All Nippon Airways",
  UA: "United Airlines",
  AA: "American Airlines",
  DL: "Delta Air Lines",
  SWA: "Southwest Airlines",
  AS: "Alaska Airlines",
  B6: "JetBlue",
  F9: "Frontier Airlines",
  NK: "Spirit Airlines",
  G4: "Allegiant Air",
  WS: "WestJet",
  AC: "Air Canada",
  QF: "Qantas",
  NZ: "Air New Zealand",
  CI: "China Airlines",
  MU: "China Eastern Airlines",
  CZ: "China Southern Airlines",
  CA: "Air China",
  HU: "Hainan Airlines",
  MF: "XiamenAir",
  VN: "Vietnam Airlines",
  AK: "AirAsia",
  OD: "Batik Air",
  GA: "Garuda Indonesia",
  PG: "Bangkok Airways",
  FD: "Thai AirAsia",
  SL: "Thai Lion Air",
  VJ: "VietJet Air",
  SB: "Air Caledonie",
  PX: "Air Niugini",
  PF: "Air Vanuatu",
  FJ: "Fiji Airways",
  TO: "Transavia",
  V7: "Volotea",
  U4: "Nesos Air",
  X3: "TUI fly",
  DE: "Condor",
  EW: "Eurowings",
  "5T": "Canadian North",
  PD: "Porter Airlines",
  ZK: "Great Lakes Airlines",
  AX: "Alaska Seaplane Service",
  K5: "SeaPort Airlines",
  "7H": "Ravn Alaska",
  "8C": "Southern Airways Express",
  "9E": "Endeavor Air",
  "9K": "Cape Air",
  QX: "Horizon Air",
  ZN: "SkyWest Airlines",
  OH: "PSA Airlines",
  YV: "Mesa Airlines",
  EV: "ExpressJet",
  PT: "Piedmont Airlines",
  B5: "SkyKing",
  J5: "Alaska Seaplane Service",
  "6E": "IndiGo",
  SG: "SpiceJet",
  I5: "AirAsia India",
  G8: "Go First",
  UK: "Air India Express",
  IX: "Air India Express",
  VT: "Air VietJet",
  AY: "Finnair",
  BT: "Air Baltic",
  LO: "LOT Polish Airlines",
  OS: "Austrian Airlines",
  SR: "Swiss",
  EN: "Air Dolomiti",
  A5: "Air France Hop",
  DB: "Air France Hop",
  YS: "Air France Hop",
  H2: "Air Caraïbes",
  SS: "Corsair",
  TZ: "Scoot",
  TR: "Scoot",
  DD: "Nok Air",
  QZ: "Indonesia AirAsia",
  PQ: "Philippines AirAsia",
  Z2: "AirAsia Philippines",
  NX: "Air Macau",
  KA: "Hong Kong Express",
  ZH: "Shenzhen Airlines",
  "3U": "Sichuan Airlines",
  "8L": "Lucky Air",
  EU: "Chengdu Airlines",
  PN: "West Air",
  G5: "China Express",
  GS: "Tianjin Airlines",
  HY: "Uzbekistan Airways",
  DV: "Air Astana",
  KC: "Air Astana",
  S7: "S7 Airlines",
  U6: "Ural Airlines",
  A4: "Azimuth",
  N4: "Nordwind Airlines",
  R3: "Yakutia Airlines",
  Y7: "Nordstar",
  EL: "Ellinair",
  A3: "Aegean Airlines",
  OA: "Olympic Air",
  FI: "Icelandair",
  WF: "Widerøe",
  DC: "Braathens Regional",
  NS: "Nova Airlines",
  JP: "Adria Airways",
  QS: "Smartwings",
  OK: "Czech Airlines",
  SP: "SATA",
  B2: "Belavia",
  "7R": "Air Baltic",
  LV: "Air Lituanica",
  ET: "Ethiopian Airlines",
  SA: "South African Airways",
  MN: "Comair",
  JE: "Mango",
  BP: "Air Botswana",
  KX: "Caribbean Airlines",
  BW: "Caribbean Airlines",
  CM: "Copa Airlines",
  LA: "LATAM Chile",
  LP: "LATAM Peru",
  XL: "LATAM Ecuador",
  "4C": "LATAM Argentina",
  JJ: "LATAM Brasil",
  SY: "Sun Country Airlines",
  QK: "Jazz Aviation",
  WG: "Sunwing Airlines",
};